name: " Custom Action"
description: "Testing Github Actions"

on:
  push:

job:
  to-print-time:
    run-on: ubuntu-latest

 steps:
      - name: Print exectuion time in formatted style
        run: |
          echo "UTC Time:"
          date -u +"%Y-%m-%dT%H:%M:%SZ"

          echo "IST Time:"
          TZ=Asia/Kolkata date +"%Y-%m-%d %H:%M:%S %Z"
