name: " Custom Action"
description: "Testing Github Actions"

on:
  workflow_dispatch:

jobs:
  print-time:
    runs-on: ubuntu-latest

    steps:
      - name: Print UTC and IST time
        run: |
          echo "UTC Time:"
          date -u +"%Y-%m-%dT%H:%M:%SZ"

          echo "IST Time:"
          TZ=Asia/Kolkata date +"%Y-%m-%d %H:%M:%S %Z"
